a= int(input('Digite o valor de a '))
b= int(input('Digite o valor de b '))
c= int(input('Digite o valor de c '))
x1= (-b+((b**2)-4*a*c)**(1/2))/(2*a)
x2= (-b-((b**2)-4*a*c)**(1/2))/(2*a)
print (x1, x2)
